name: Rassegna Stampa

on:
  schedule:
    - cron: "00 00 * * *"  # Runs daily at 00:00 UTC (01:00 ora solare - 02:00 ora legale)
    - cron: "00 08 * * *"  # Runs daily at 09:30 UTC (09:00 ora solare - 10:00 ora legale)
    - cron: "00 12 * * *"  # Runs daily at 13:30 UTC (13:00 ora solare - 14:00 ora legale)
    - cron: "00 16 * * *"  # Runs daily at 17:30 UTC (17:00 ora solare - 18:00 ora legale)
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests pytz

    - name: Execute Python Script
      env:  # Pass secrets as environment variables
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python WeAreRoma.py

    # Commit and push changes to `sent_articles.log`
    - name: Commit changes
      if: success()
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add sent_articles.log
        git commit -m "Aggiornamento sent_articles.log"
        git push
        
