name: Rassegna Stampa

on:
  schedule:
    # Trigger every hour
    - cron: "0 * * * *"
    - cron: "10 * * * *"
    - cron: "20 * * * *"
    - cron: "30 * * * *"
    - cron: "40 * * * *"
    - cron: "50 * * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  check-run:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.check_local_time.outputs.run }}
    steps:
      - name: Check local time
        id: check_local_time
        env:
          TRIGGER: ${{ github.event_name }}
        run: |
          echo "Trigger: ${TRIGGER}"
          if [[ "${TRIGGER}" == 'schedule' ]]; then
            # Check local time in Europe/Rome
            CURRENT_HOUR=$(TZ=Europe/Rome date +%H)
            echo "Current hour in Europe/Rome: ${CURRENT_HOUR}"
            if [[ "${CURRENT_HOUR}" == "01" || "${CURRENT_HOUR}" == "09" || "${CURRENT_HOUR}" == "13" || "${CURRENT_HOUR}" == "17" ]]; then
              echo "Time matches desired hour (${CURRENT_HOUR}:00)."
              echo "run=True" >> "$GITHUB_OUTPUT"
            else
              echo "Not a desired hour. Current local time: ${CURRENT_HOUR}:00"
              echo "run=False" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "Manual trigger, bypassing time check."
            echo "run=True" >> "$GITHUB_OUTPUT"
          fi

  run-script:
    runs-on: ubuntu-latest
    needs: check-run
    if: needs.check-run.outputs.run == 'True'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests pytz

      - name: Execute Python Script
        env:  # Pass secrets as environment variables
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python WeAreRoma.py

      # Commit and push changes to `sent_articles.log`
      - name: Commit changes
        if: success()
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add sent_articles.log
          git commit -m "Aggiornamento sent_articles.log"
          git push
